const vestidos = [
    {
        id: "1",
        modelo: "Vestidos",
        nome:"Cropped Rendado",
        valor: 1559,
        imagem: "./img/vestidos/vestido-de-noiva1.jpg",
    },
    {
        id: "2",
        modelo: "Vestidos",
        nome:"Vestido Renda",
        valor: 1795,
        imagem: "./img/vestidos/vestido de noiva 2.jpg",
    },
    {
        id: "3",
        modelo: "Vestidos",
        nome:"Vestido Manga",
        valor: 1489,
        imagem: "./img/vestidos/vestido de noiva 3.jpg",
    },
    {
        id: "4",
        modelo: "Vestidos",
        nome:"Vestido Rendado",
        valor: 1625,
        imagem: "./img/vestidos/vestido de noiva 4.jpeg",
    },
    {
        id: "5",
        modelo: "Vestidos",
        nome:"Branco Gelo",
        valor: 1567,
        imagem: "./img/vestidos/vestido-de-noiva 5.jpg",
    },
    {
        id: "6",
        modelo: "Vestidos",
        nome:"Bege Rendado",
        valor: 1899,
        imagem: "./img/vestidos/vestido de noiva 6.jpg",
    },
    {
        id: "7",
        modelo: "Vestidos",
        nome:"Cropped Manga",
        valor: 1659,
        imagem: "./img/vestidos/vestido de noiva 7.jpeg",
    },
    {
        id: "8",
        modelo: "Vestidos",
        nome:"Sereia Rendado",
        valor: 1996,
        imagem: "./img/vestidos/vestido de noiva 8.jpg",
    },
    {
        id: "9",
        modelo: "Vestidos",
        nome:"Vestido Rendado",
        valor: 1853,
        imagem: "./img/vestidos/vestido de noiva 9.jpg",
    },
    {
        id: "10",
        modelo: "Vestidos",
        nome:"Rendado Manga",
        valor: 1999,
        imagem: "./img/vestidos/vestido de noiva 10.jpeg",
    },
    {
        id: "11",
        modelo: "Veu",
        nome:"Glitter",
        valor: 900,
        imagem: "./img/veu/veu 1.jpeg",
    },
    {
        id: "12",
        modelo: "Veu",
        nome:"Ramos Renda",
        valor: 500,
        imagem: "./img/veu/veu 2.jpeg",
    },
    {
        id: "13",
        modelo: "Veu",
        nome:"Barra Rendada",
        valor: 300,
        imagem: "./img/veu/veu 3.jpeg",
    },
    {
        id: "14",
        modelo: "Veu",
        nome:"Pequenos Ramos",
        valor: 200,
        imagem: "./img/veu/veu 4.jpg",
    },
    {
        id: "15",
        modelo: "Veu",
        nome:"Véu Pedrarias",
        valor: 500,
        imagem: "./img/veu/veu 5.jpeg",
    },
    {
        id: "16",
        modelo: "Veu",
        nome:"Véu Rendas",
        valor: 700,
        imagem: "./img/veu/veu 6.jpg",
    },
    {
        id: "17",
        modelo: "Veu",
        nome:"Simples Glitter",
        valor: 200,
        imagem: "./img/veu/veu 7.jpeg",
    },
    {
        id: "18",
        modelo: "Veu",
        nome:"Pedrarias e Renda",
        valor: 900,
        imagem: "./img/veu/veu 8.jpg",
    },
    {
        id: "19",
        modelo: "Veu",
        nome:"Simples Pedrarias",
        valor: 500,
        imagem: "./img/veu/veu 9.jpeg",
    },
    {
        id: "20",
        modelo: "Veu",
        nome:"Simples Rendas",
        valor: 200,
        imagem: "./img/veu/veu 10.jpg",
    },
    {
        id: "21",
        modelo: "Acessorios",
        nome:"Tiara Pedraria",
        valor: 150,
        imagem: "./img/acessorios/acessorio 1.jpg",
    },
    {
        id: "22",
        modelo: "Acessorios",
        nome:"Coroa",
        valor: 200,
        imagem: "./img/acessorios/acessorio 2.jpeg",
    },
    {
        id: "23",
        modelo: "Acessorios",
        nome:"Arranjo",
        valor: 100,
        imagem: "./img/acessorios/acessorio 3.jpeg",
    },
    {
        id: "24",
        modelo: "Acessorios",
        nome:"Coroa Pedrarias",
        valor: 200,
        imagem: "./img/acessorios/acessorio 4.jpeg",
    },
    {
        id: "25",
        modelo: "Acessorios",
        nome:"Tiara com Ramos",
        valor: 300,
        imagem: "./img/acessorios/acessorios 5.jpeg",
    },
    {
        id: "26",
        modelo: "Acessorios",
        nome:"Pedraria Dourado",
        valor: 200,
        imagem: "./img/acessorios/brinco 1.jpg",
    },
    {
        id: "27",
        modelo: "Acessorios",
        nome:"Prata Pedraria",
        valor: 250,
        imagem: "./img/acessorios/brinco 2.jpg",
    },
    {
        id: "28",
        modelo: "Acessorios",
        nome:"Brinco Pedraria",
        valor: 300,
        imagem: "./img/acessorios/brinco 3.jpeg",
    },
    {
        id: "29",
        modelo: "Acessorios",
        nome:"Brinco Pedraria",
        valor: 250,
        imagem: "./img/acessorios/brinco 4.jpeg",
    },
    {
        id: "30",
        modelo: "Acessorios",
        nome:"Brinco Brilhante",
        valor: 150,
        imagem: "./img/acessorios/brinco 5.jpeg",
    },
    {
        id: "31",
        modelo: "Acessorios",
        nome:"Dourado Pedraria",
        valor: 200,
        imagem: "./img/acessorios/colar 1.jpg",
    },
    {
        id: "32",
        modelo: "Acessorios",
        nome:"Colar em Pedraria",
        valor: 250,
        imagem: "./img/acessorios/colar 2.jpg",
    },
    {
        id: "33",
        modelo: "Acessorios",
        nome:"Gargantilha",
        valor: 300,
        imagem: "./img/acessorios/colar 3.jpg",
    },
    {
        id: "34",
        modelo: "Acessorios",
        nome:"Gargantilha",
        valor: 250,
        imagem: "./img/acessorios/colar 4.jpg",
    },
    {
        id: "35",
        modelo: "Acessorios",
        nome:"Colar Pedraria",
        valor: 150,
        imagem: "./img/acessorios/colar 5.jpeg",
    },
    {
        id: "36",
        modelo: "Sapatos da Noiva",
        nome:"Strass e Pedraria",
        valor: 500,
        imagem: "./img/sapatos/sapato 1.png",
    },
    {
        id: "37",
        modelo: "Sapatos da Noiva",
        nome:"Sapato Laço",
        valor: 600,
        imagem: "./img/sapatos/sapato 2.png",
    },
    {
        id: "38",
        modelo: "Sapatos da Noiva",
        nome:"Branco Floral",
        valor: 400,
        imagem: "./img/sapatos/sapato 3.jpeg",
    },
    {
        id: "39",
        modelo: "Sapatos da Noiva",
        nome:"Sapato Glitter",
        valor: 800,
        imagem: "./img/sapatos/sapato 4.jpg",
    },
    {
        id: "40",
        modelo: "Sapatos da Noiva",
        nome:"Sapato Pedraria",
        valor: 700,
        imagem: "./img/sapatos/sapato 5.jpg",
    },
    {
        id: "41",
        modelo: "Sapatos da Noiva",
        nome:"Strass e Pedraria",
        valor: 800,
        imagem: "./img/sapatos/sapato 6.jpg",
    },
    {
        id: "42",
        modelo: "Sapatos da Noiva",
        nome:"Pedraria e Floral",
        valor: 600,
        imagem: "./img/sapatos/sapato 7.jpeg",
    },
    {
        id: "43",
        modelo: "Sapatos da Noiva",
        nome:"Sapato Floral",
        valor: 400,
        imagem: "./img/sapatos/sapato 8.jpg",
    },
    {
        id: "44",
        modelo: "Sapatos da Noiva",
        nome:"Todo em Pedraria",
        valor: 900,
        imagem: "./img/sapatos/sapato 9.jpg",
    },
    {
        id: "45",
        modelo: "Sapatos da Noiva",
        nome:"Laço e Pedraria",
        valor: 300,
        imagem: "./img/sapatos/sapato 10.jpg",
    },
    {
        id: "46",
        modelo: "Ternos",
        nome:"Terno Preto",
        valor: 1505,
        imagem: "./img/terno/terno 1.jpg",
    },
    {
        id: "47",
        modelo: "Ternos",
        nome:"Terno Cinza",
        valor: 1706,
        imagem: "./img/terno/terno 2.jpg",
    },
    {
        id: "48",
        modelo: "Ternos",
        nome:"Terno Azul",
        valor: 1302,
        imagem: "./img/terno/terno 3.jpg",
    },
    {
        id: "49",
        modelo: "Ternos",
        nome:"Terno Preto",
        valor: 1209,
        imagem: "./img/terno/terno 4.jpg",
    },
    {
        id: "50",
        modelo: "Ternos",
        nome:"Terno Azul Royal",
        valor: 1608,
        imagem: "./img/terno/terno 5.jpg",
    },
    {
        id: "51",
        modelo: "Ternos",
        nome:"Terno Bege",
        valor: 1805,
        imagem: "./img/terno/terno 6.jpg",
    },
    {
        id: "52",
        modelo: "Ternos",
        nome:"Terno Skinny",
        valor: 1706,
        imagem: "./img/terno/terno 7.jpg",
    },
    {
        id: "53",
        modelo: "Ternos",
        nome:"Terno Verde",
        valor: 1405,
        imagem: "./img/terno/terno 8.jpg",
    },
    {
        id: "54",
        modelo: "Ternos",
        nome:"Terno Azul Claro",
        valor: 1201,
        imagem: "./img/terno/terno 9.png",
    },
    {
        id: "55",
        modelo: "Ternos",
        nome:"Verde Claro",
        valor: 1307,
        imagem: "./img/terno/terno 10.jpg",
    },
    {
        id: "56",
        modelo: "Gravata",
        nome:"Gravata Preta",
        valor: 150,
        imagem: "./img/gravata/gravata 1.jpg",
    },
    {
        id: "57",
        modelo: "Gravata",
        nome:"Borboleta",
        valor: 200,
        imagem: "./img/gravata/gravata 2.jpg",
    },
    {
        id: "58",
        modelo: "Gravata",
        nome:"Gravata Prata",
        valor: 300,
        imagem: "./img/gravata/gravata 3.jpg",
    },
    {
        id: "59",
        modelo: "Gravata",
        nome:"Gravata Rosé",
        valor: 250,
        imagem: "./img/gravata/gravata 4.jpeg",
    },
    {
        id: "60",
        modelo: "Gravata",
        nome:"Borboleta Vinho",
        valor: 200,
        imagem: "./img/gravata/gravata 5.png",
    },
    {
        id: "61",
        modelo: "Gravata",
        nome:"Borb. Dourada",
        valor: 400,
        imagem: "./img/gravata/gravata 6.jpg",
    },
    {
        id: "62",
        modelo: "Gravata",
        nome:"Gravata Dourada",
        valor: 350,
        imagem: "./img/gravata/gravata 7.jpg",
    },
    {
        id: "63",
        modelo: "Gravata",
        nome:"Gravata Rosa",
        valor: 230,
        imagem: "./img/gravata/gravata 8.jpeg",
    },
    {
        id: "64",
        modelo: "Gravata",
        nome:"Rosa Bebê",
        valor: 240,
        imagem: "./img/gravata/gravata 9.jpg",
    },
    {
        id: "65",
        modelo: "Gravata",
        nome:"Gravata Cinza",
        valor: 150,
        imagem: "./img/gravata/gravata 10.jpg",
    },
    {
        id: "66",
        modelo: "Relogio",
        nome:"Relógio Azul",
        valor: 350,
        imagem: "./img/relogio/relogio 1.jpg",
    },
    {
        id: "67",
        modelo: "Relogio",
        nome:"Marrom Dourado",
        valor: 200,
        imagem: "./img/relogio/relogio 2.jpg",
    },
    {
        id: "68",
        modelo: "Relogio",
        nome:"Relógio Preto",
        valor: 150,
        imagem: "./img/relogio/relogio 3.jpg",
    },
    {
        id: "69",
        modelo: "Relogio",
        nome:"Relógio Prata",
        valor: 100,
        imagem: "./img/relogio/relogio 4.jpeg",
    },
    {
        id: "70",
        modelo: "Relogio",
        nome:"Azul e Prata",
        valor: 200,
        imagem: "./img/relogio/relogio 5.jpg",
    },
    {
        id: "71",
        modelo: "Relogio",
        nome:"Preto e Bronze",
        valor: 400,
        imagem: "./img/relogio/relogio 6.jpeg",
    },
    {
        id: "72",
        modelo: "Relogio",
        nome:"Marrom e Prata",
        valor: 300,
        imagem: "./img/relogio/relogio 7.jpeg",
    },
    {
        id: "73",
        modelo: "Relogio",
        nome:"Veludo Marrom",
        valor: 230,
        imagem: "./img/relogio/relogio 8.jpeg",
    },
    {
        id: "74",
        modelo: "Relogio",
        nome:"Preto e Vermelho",
        valor: 340,
        imagem: "./img/relogio/relogio 9.png",
    },
    {
        id: "75",
        modelo: "Relogio",
        nome:"Preto e Dourado",
        valor: 350,
        imagem: "./img/relogio/relogio 10.jpg",
    },
    {
        id: "76",
        modelo: "Sapato Noivo",
        nome:"Preto e Cinza",
        valor: 600,
        imagem: "./img/sapato noivo/sapato 1.jpeg",
    },
    {
        id: "77",
        modelo: "Sapato Noivo",
        nome:"Preto e Prata",
        valor: 550,
        imagem: "./img/sapato noivo/sapato 2.jpeg",
    },
    {
        id: "78",
        modelo: "Sapato Noivo",
        nome:"Preto Fosco",
        valor: 500,
        imagem: "./img/sapato noivo/sapato 3.jpeg",
    },
    {
        id: "79",
        modelo: "Sapato Noivo",
        nome:"Preto Simples",
        valor: 300,
        imagem: "./img/sapato noivo/sapato 4.jpg",
    },
    {
        id: "80",
        modelo: "Sapato Noivo",
        nome:"Preto Detalhes",
        valor: 350,
        imagem: "./img/sapato noivo/sapato 5.jpg",
    },
    {
        id: "81",
        modelo: "Sapato Noivo",
        nome:"Sapato Marrom",
        valor: 300,
        imagem: "./img/sapato noivo/sapato 6.jpg",
    },
    {
        id: "82",
        modelo: "Sapato Noivo",
        nome:"Fosco Detalhe",
        valor: 300,
        imagem: "./img/sapato noivo/sapato 7.jpg",
    },
    {
        id: "83",
        modelo: "Sapato Noivo",
        nome:"Brilhante Detalhe",
        valor: 420,
        imagem: "./img/sapato noivo/sapato 8.png",
    },
    {
        id: "84",
        modelo: "Sapato Noivo",
        nome:"Preto Prata",
        valor: 530,
        imagem: "./img/sapato noivo/sapato 9.jpg",
    },
    {
        id: "85",
        modelo: "Sapato Noivo",
        nome:"Marrom",
        valor: 450,
        imagem: "./img/sapato noivo/sapato 10.jpg",
    },
]